### ISSUE TITLE
cant save합니다 빈앨님

### ISSUE THREAD

**Issue by hyunseo777** [alvin0319/NPC#1]
TypeError: "Argument 1 passed to pocketmine\nbt\tag\CompoundTag::setTag() must be an instance of pocketmine\nbt\tag\NamedTag, string given, called in /mnt/c/Users/hyuns/MCPE server/plugins/NPC-stable/src/alvin0319/NPC/entity/NPCHuman.php on line 120" (EXCEPTION) in "vendor/pocketmine/nbt/src/tag/CompoundTag" at line 135

서버 끌시 오류나면서 그동안 작업한 NPC파일에 저장이 되지 않습니다.
php 사용버전: 7.3
서버 api: 3.11.3

**Comment by alvin0319** [comment]
https://github.com/alvin0319/NPC/commit/454fc66cb4d04c7c97084cab21575f7720a5546d 에서 고쳐졌습니다. 재 설치해주세요.
