### ISSUE TITLE
Npc stop the server 

### ISSUE THREAD

**Issue by HaithamJB** [alvin0319/NPC#13]
Issue Description
When two player go close to the npc the server crash
Your System information
I uso minehub to hoste
--------------------------

*I use android /window 10
* Your PocketMine-MP Version: 

* Plugin Version: 
NPC v1.0.2

Code:

Backtrace:

PocketMine-MP version: 3.12.0 [Protocol 390]
Git commit: 77d45bf11674a1360f58e32a14a3b09f423d860c
uname -a: Linux 1ce6636e4a86 4.19.0-0.bpo.6-amd64 #1 SMP Debian 4.19.67-2+deb10u1~bpo9+1 (2019-09-30) x86_64
PHP Version: 7.3.6
Zend version: 3.3.6
OS : Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: NPC v1.0.2

===BEGIN CRASH DUMP===
eNq1Wm1zozgS/isu39bVbm2MAb/F+XLlOMlMduKML/a83A5bKRlkozEgVggnZGvut1+LV4nkxnaW
mcok0EDreboldaulv9prynzE73eYRYQG7TPzpM2Jj9tnxuB0NB73++bgpI0Zo6x99lebJyE8al/e
X97dvb9rn7R9HEVoI2S3OOIk2LQ8vMNei1PacjAOW50Ww3YMyncYBCEOHBzYyb/g0zXxxHehF29I
EHVv59MvE29HAr1njP9o/Wz8ooUuYt2I2V1UyMVbXRxwwpPuZfrnHEUYlHkkEJhN49tJrvGeBDvq
7bAPr0MzDgEcvF08FYDnU7i1qQMffvkDaDNk55cbHGCGPME4QMIY7Tm1t5jPoJXObA6fraDZymjt
nmaYmi7kMfEcADIa907aJLp38K59tkZehKFlRjm1KajtjXVohAhco5HTH6zWhjEc9ZHRG+rrwSnu
mcjoo95KH6/7Zs85Heo26GZo65EVfKMXrcU5uhsSxI8tw8bDYW+I++h02OprxljTO7q2Cqk27CDf
GfZb/zBai9m8dYFXBAXZK8NRx/zVwStDj43/wrvjX43Wz6ZujDv6uNPTf2k9ng7vh31hODcUeLWe
NoS7J/BkSjy7hYf3NCqggCC98dKb0iWRMOi5sBBmS0q9SDKwIj5pV6Y1NODaWWGOTJCjmLuUwYdf
2tMnbLvz2QXeiQ8+kkeynf7eBu+hkIjnPU0HI8E9DtDKw4CWsxjckPXCKPN0RNf8Qhb4KO0ctlAe
+uC+yLJWGTYusFlWDalHkTDE/P1i+en93c0FiB7wKiJcsHI5D6Ozbhd87cYrzaZ+V4LdVVSBmc49
Sp2rz7JZcolqEV2r2eIj8vDY6DfFPlcHXLPmLWsmHuwhKxjMYo+TT5SJQVCSkIQqj4FmHOJTmCvi
JOZRvCVwvUUeIdvoh3jaF0gfBFKgLKP+O16WFIGFxLRTmSabhL7r23Lya4pxqdCyoPn01zybFA9w
8Bzm+CXayFNjLpFp6FpfJfEh2Ab0IThHHswJTRFRlFpWDqS8OIhOzPAcM1+eiiqZ6pm+1lNJDftX
V7re+mdrzuhXiC7XwZoEEJOa4nefNQCECkTS5Ss6ZfptHm4rPWCFqUe5i2UbFBLZAqZmpFFHssAy
DjYRx8HHxnxaabSsHER5cYhDF9sEJi17K3EpRTKZDKRC5g0ERf7vGDH+1BQbRqlvjCyrgFBd7ePC
HwjnmKV+k4EBxXQqgS7HRUJT0VTEqt962ml9TiGxlzQ3oQhtlpVOnGGGoB4yFsvJ3fLDfF8XncWE
rQn2nG6YZly+yLiKFJEzjLs+gu7BugpbMZAp45BmzS+VpK2QqQPZqIcdL7aReRpi3pRFypYPj5yX
m80nxOQxWEjq8SHLhmoUJrcXd5eTz6YpUejnffxvUcGbzQOgsKwKzne5hB5KNAwuCiCJ8ENIuzUc
nxljo2emfoLHmE0cXyivPCVJn9E9JBwaRiPxUMKh3Bw083BE2AIjeUxWsnooqbHaUoYcOugZ/kjh
NX49LUklTDsFEOny0Pg4dRVOpahOyTBeCo9HDSkp9j5j1r5CNofWIhj10NBnvCM0hiHWKeTt/xM5
BdjqqoG4maoRYTOOOPUnDCMldErS+kLmR887UtuHzTwvsC1BdWUmIu4gFn64liNOJlDDaq9O8jMO
CPIuUNDYgH1MNToIxmgGwbJugCRmBw1TN/a2mJ3TR3mcVsL69FNjcx77q9jfEs9rymeVRhibJY7D
A8d1sFtgLJHJBXvm0TQLeUsZecqHTiNcZKWWlSE5xjskD+lZuSknJAnVvvYskN9cfG6KCqiyrKrl
Vw8n0NOZTeeXXYlFutRHTyS4giRMXuwXMtV3p9pIpUnIlYd8QgLxBW6KsapVLP5zONLlIT68IRuX
B7AGu4Ag40r8ag/qSVlt3QuJ5C5Cnpiw/fhP0F+fP/qvJVpotiyvQOQIRIf5WHxpM7Tm2mOS5uOT
mNOphxG7QRt5YazK9yw+lg8E8lqnKV/yTJ1lQRPUFiA8AGFZdUzH9uYc5iRKvNifTbuqPtGvRUnr
HHHu4Xp1L5fumZcuGNrQQOReT7Np64o8Yqc1m04h9Q8x+8+yKQO9QwS69flBmblNA+onk7kc+ySh
TGigjer9mAZ4Bf+bAp6rsyycIQCdkJvLaPYTmnaWomElmEvCZwOzEzKskGqIy8J2Hfpw+/H64noC
JKZLEcoPjXtvMQxEV61FVTJ1Afysly1c7HnJ6GHUlFuiQqFllSAO57LYJrXFXyHZk0GmJdK3F02x
2Al1Lkwb0TbJVn0VjmOnijfIR9vp791CQ7n4W2AvDYPRswVg9aQ+SdQC4MQZ6LrRFOtMW7HgK0Ec
7r452WySLFu+DGwXBVzh9sLTel1tUJsEEXz0Jk7qIc98LcVCoSiOPkPzovAVHi8a6b6grivshKNI
bN4hL1rOJQMp4nqHN3/ExCO3CDOp2v7+0Uo2wQIzwAlracXV9Sd76k6MrqItvjcMvbmCY6ERhu5i
Ab+eITq4hKqEB0lYH5u12uI1f0oTveTIaamq036Hn6S8qqUeEzWEPbLqXM1tubDusdo+xnjsYZp2
6U1TLisVjseZuzIkr15wSBC7EjGxOUcCfIcjLFdzKpmaoJr1iHmFvG1TlNegi7Ct2HCD5ploHuhK
SPa6UaoFnWOOJEL1J/uqVEvMXYDg3P89cu0JzCCLEPmiOlUxldBYVn5zcFflaL2epecT5IJiLqt3
1Jq7blEEPUBEtKiWNPfzmnAv/2vmf4387/D1fpUaha48E/8PIfqG0TiMlOmmFO1ZLUxd5Ifv15Br
4MaKGLJOyyqQHLEHjthWHWOZoBbZVCJvfR9+4N9xVTJ5HfIdSq7vu0I5DLgUiyCTYzp2eimAdnMN
og7q4ogvXBrKVdBSpqY6ZnpcRCIuhn26nMbst/ntcRHjMPIlFMuSUR1LPKQbuOtQFkIfRxvcrZSJ
wQrp/8RTgkou2dODJ4EjCqxv37z7Edwr7TAYM0DlxSF9+Q6HiLA7LDgpA7T24PtnGCApWDHkEn+2
MMQeulxE/QGkSdaYZakgjxjBydyjygjOBCrLoWbUDgR8IvgJJJePj4iJt07aX1FEg4ckCGopXv/o
+KIs8fPjaDTAoiJ3Weav6VbnxeVHkjef7pIueOKl1ddLFCVT6vsocETdZp0XsXOrZRzBSAXX7+zc
pmUvZ4cCGzvviJICK2K1NNKr9/2G9j9eXGHJy7sKUQO7IgrBb+JwW7lTrSW+J6wDANOUWwsZDTHj
RJytEOIQMbASTHU5D/zIcRClm1dgwSllWDpi5yAu34KmIIo8SRLayvvRnx7A78mH9LLzgsXtyvbT
gmwpsJEHJkRMFrEk5DQ9wpPt5Nj5mc/yhZjJGL5G+WgYpc6FPgXspOdrLp8a3DjyjS8/ciF3kMlw
JJDJ7y/mN9Jdes7UyY5DZmURfxVxRiAxr17yEzBKelAxv2oNxJaO2XHwrtVpmbox0Pv6CC5/unbO
WiPbhp/xEA9Hg/XQGZl4YK/1tTkcrfun2BiObBOtVmav9VNq/YDLlpi7iiGrXnFvu3GwjTkRBx7F
4c3UUiGNyKP8Pndhphb9Oc3JDHFy9KSdH56lwSbOjFF8fofXokyRDa3SaK5PZZtGKYZI7lNRvqwe
ww3ZrEiAWJJXpIUNOd3igDwpLkxQ2qtFFU2shp5ImKWcg/Q2NSwpX//27X+41B76
===END CRASH DUMP===

**Comment by alvin0319** [comment]
Without your PocketMine-MP version and NPC version, I can't fix this error.
