### ISSUE TITLE
Applying skin and geometry on CustomEntity

### ISSUE THREAD

**Issue by Endermanbugzjfc** [alvin0319/NPC#23]
I have a question, **how can I apply skin and geometry on `CustomEntity`**? 

I checked the source code of the `CustomEntity` class and `BaseEntity` class found that there is no skin property in these two classes and they don't extend from the Pocketmine-MP `Entity` class either. 

Do I use the `NPCHuman` class if I want to apply skin and geometry?

**Comment by alvin0319** [comment]
/npc create npc `nametag` `path/to/your/image` `path/to/your/geometry`

**Comment by alvin0319** [comment]
Also, you **can't** apply skin to `CustomEntity` because CustomEntity isn't use SkinPacket.
