### ISSUE TITLE
The plugin doesn't load

### ISSUE THREAD

**Issue by BrahmjotSingh0** [alvin0319/NPC#24]
This plugin doesn't work in my servers I think it is not loading and it can't be seen by /pl.
I tried lot of times but not working
It doesn't create plugin data in folder.

**Comment by alvin0319** [comment]
I need more information like your NPCs version, PocketMine-MP version...

**Comment by BrahmjotSingh0** [comment]
I m using latest version of pocketmine and npc both
Pocketmine : 3.15.1
Npc: latest

**Comment by BrahmjotSingh0** [comment]
Any place where i can contact u?

**Comment by alvin0319** [comment]
@RealBJsingh https://t.me/alvin0319
