### ISSUE TITLE
Server Crashes after 30 minutes

### ISSUE THREAD

**Issue by ghost** [alvin0319/NPC#4]
13:52:19] [Server thread / EMERGENCY]: An unrecoverable error has occurred and the server crashed.  Create a crash dump ...

 [13:52:19] [Server thread / EMERGENCY]: Please upload the "/home/minecraft/crashdumps/Mon_Jan_6-13.52.19-CET_2020.log" file into the crash archive and submit the link on the bug  Reporting page.  Provide as much information as possible.

**Comment by ghost** [comment]
Fatal error: Nesting level too deep - recursive dependency? in phar:///home/minecraft/plugins/NPC_dev-6.phar/src/alvin0319/NPC/entity/EntityBase.php on line 121

**Comment by alvin0319** [comment]
@DragonfireHD I don't know why this error occurred.

**Comment by alvin0319** [comment]
@DragonfireHD Maybe I should create a new structure.

**Comment by ghost** [comment]
Ok but i testing this plugin and he crashed my server your plugin is very nice

**Comment by ghost** [comment]
Raise pcre.recursion_limit at php.ini

**Comment by alvin0319** [comment]
@debian44 How much should I raise?

**Comment by ghost** [comment]
I find a webadress for this

Check then out https://github.com/IlchCMS/Ilch-1.2/wiki/Doc-pcre.recursion_limit-auf-Windows-Servern

**Comment by ghost** [comment]
@DragonfireHD I speak English worse than anyone you know so forget German
@alvin0319 and raise it till that warning disappears

**Comment by ghost** [comment]
I googled about that its default is 100000 so its actually raised by default.
You should rewrite your EntityBase, PMMP is using 2 ~ 10 preg_* functions for your job and you use that in a foreach() loop and you use getClosestPlayer() continuously so I recommend taking a look at jojoe77777 SlapperRotation plugin which uses PlayerMoveEvent for this its better because you don't re-calculate afk guys coordination
Another suggest is using Async Tasks. Create an repeating async task with delay of 20 ~ 40 ticks (or configurable) this task should get moved players in 20 ticks ago list, delete another level players from list, calculate distances, arsort()s and finally gives you a Player to lookAt($thatGuy::asVector3()) (// asVector3 isn't required)

**Comment by alvin0319** [comment]
@debian44 I think using PlayerMoveEvent is same as 1 tick tasking, but i know that i should rewrite my entity base. thank you for reply and advise.

**Comment by alvin0319** [comment]
Probably solved at https://github.com/alvin0319/NPC/commit/dbfe77b35358fa1ee122ad1be79d8e319a377431 . If you get this error again, please report it to Issue Tracker.
