### ISSUE TITLE
Mobs + Non-NPC

### ISSUE THREAD

**Issue by lentou** [alvin0319/NPC#5]
When I create another villager or any mob, The 1 Mob will be vanish

For Non-NPC like when i hit players or mobs the Message
"[NPC] This Entity is not a NPC"

**Comment by alvin0319** [comment]
@Lentou Can you give me more accurate information?

**Comment by lentou** [comment]
When i create more villagers or any mobs i think It will be stack in one, but for Human it not stack.

Everytime I'm hitting a player or mobs, the message  "[NPC] This Entity is not a NPC"

**Comment by alvin0319** [comment]
@Lentou Did you touch in remove mode?
