### ISSUE TITLE
Npc Automatically dispawn

### ISSUE THREAD

**Issue by ghost** [alvin0319/NPC#6]
The Npcs just disappear and I need to reposition the replace please fix the rest is good

**Comment by alvin0319** [comment]
@DragonfireHD Please give me more informations

**Comment by Adam1609** [comment]
Do you have ClearLagg installed?

**Comment by alvin0319** [comment]
@Adam1609 My plugin's npcs does not delete by ClearLagg

**Comment by alvin0319** [comment]
Close this issue because It doesn't have any information.
